FROM debian:12-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    pkg-config \
    git \
    curl \
    libcurl4-openssl-dev \
    libeigen3-dev \
    libsamplerate0-dev \
    python3 \
    python3-pip \
    python3-full \
    python3-venv \
    python3-dev \
    python3-pip \
    ffmpeg \
    libavcodec-dev \
    libavformat-dev \
    libavutil-dev \
    libswresample-dev \
    libswscale-dev \
    libmp3lame-dev \
    libvorbis-dev \
    libopus-dev \
    && rm -rf /var/lib/apt/lists/*

CMD ["/bin/bash"]


